# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180124_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Under Review'), (3, 'Solved')], default='', max_length=200),
        ),
    ]
