# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Solved', 'Solved')], default='', max_length=200),
        ),
    ]
