# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20180125_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], default='', max_length=50),
        ),
    ]
