# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20180125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
