# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.Board'),
            preserve_default=False,
        ),
    ]
